
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Top from "@/components/Top";
import Nav from "@/components/Nav";
import ReduxProvider from "@/redux/Provider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",  // changed to --font-inter
  subsets: ["latin"],
  weight: ['500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 




  return (
    <html lang="en" className={`${inter.variable} ${inter.variable} ${inter.variable}`}>
      {/* Added all font variables on html for global use */}
      <body className="antialiased">
        <ReduxProvider>
          <Top />
          <Nav />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
